version: "3.2"
services:
  web:
    build: .
    ports:
     - "8081:8081"
    volumes:
     - .:/code
    depends_on:
     - redis
    expose:
     - "8081"
    hostname: web
    container_name: web
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
  redis:
    image: "redis:3.2.9"
    command: redis-server --requirepass supersecret
    ports:
     - "6379:6379"
    volumes:
     - $PWD/redis-data:/var/lib/redis
     - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master
    expose:
     - "6379"
    hostname: redis
    container_name: redis
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    hostname: nginx
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
